### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mds4mstuke** [meteorhacks/meteor-aggregate#10]
Many thanks for the package! I think the version specification may be off, updating via "meteor update" jumps this to 1.2.0 instead of 1.1.1 as listed in packages.js. Forcing update to 1.1.1 works, just wanted to give a heads up.

Cheers,
-Mike

**Comment by arunoda** [comment]
Oh. May be. I forgot to push the new version :)

**Comment by arunoda** [comment]
Okay. Pushed the new version to GH.

**Comment by mds4mstuke** [comment]
Sweet -- thanks!
