### ISSUE TITLE
Usage with Meteor.users

### ISSUE THREAD

**Issue by tanis2000** [meteorhacks/meteor-aggregate#2]
Is it possible to use this package with Meteor.users? 
I tried the following code:

```
  var metrics = Meteor.users;
  var pipeline = [
    {$group: {_id: null, month: {$month: "$createdAt"}}}
  ];
  var result = metrics.aggregate(pipeline);
  return result;
```

But it throws this error:

```
I20141106-17:30:35.662(1)? Exception while invoking method 'aggregatedSignups' TypeError: Object #<Object> has no method 'aggregate'
I20141106-17:30:35.662(1)?     at Mongo.Collection.aggregate (packages/meteorhacks:aggregate/index.js:21)
I20141106-17:30:35.662(1)?     at Object.App.Admin.aggregatedSignups (packages/app-admin/server/charts.js:6)
I20141106-17:30:35.662(1)?     at Meteor.methods.aggregatedSignups (packages/app-admin/server/charts.js:13)
I20141106-17:30:35.663(1)?     at methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:179)
I20141106-17:30:35.663(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599)
I20141106-17:30:35.663(1)?     at packages/ddp/livedata_server.js:648
I20141106-17:30:35.663(1)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20141106-17:30:35.663(1)?     at packages/ddp/livedata_server.js:647
I20141106-17:30:35.663(1)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20141106-17:30:35.663(1)?     at _.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646)
```

**Comment by arunoda** [comment]
Now you can do this.

**Comment by aashiqerasool** [comment]
This does not seem to be working for me. I have an almost similar method except that my pipeline is slightly different. However I receive the same error.

**Comment by mwarren2** [comment]
I also cannot get it to work with **Meteor.users**

In my **/server** folder I have my **publications.js** file. 
It contains this very simple code (I kept eliminating complications to get it right down the simplest form to illustrate the problem):
    
    Meteor.publish('orders', function() {
        var wot = Meteor.users.aggregate([{$match: {}}]);
        return wot;
    }

And I get this error:

    Exception from sub orders id F938tbFmfuEGsyjbG TypeError: Object [object Object] has no method 'aggregate'

**Comment by sairamdevarashetty** [comment]
+1 It is still not working for met too

**Comment by sachin-rajput** [comment]
It might be a wrapping problem, something is probably wrapping Meteor.users directly (not Mongo.Collection).

Here is what I tried manually and worked for me:

```
    var rawUsers = Meteor.users.rawCollection();
    var aggregateQuery = Meteor.wrapAsync(rawUsers.aggregate, rawUsers);
    var pipeline = [
        {$match: {}},
        {$project: {username: 1, profile: 1}}
    ];
    var result = aggregateQuery(pipeline);

    return result;
```

Read more about [Meteor.wrapAsync here](https://docs.meteor.com/api/core.html#Meteor-wrapAsync)
