### ISSUE TITLE
Exception while simulating the effect of invoking 'Collection' TypeError: Collection.aggregate is not a function

### ISSUE THREAD

**Issue by suryaiiit** [meteorhacks/meteor-aggregate#20]
Exception while simulating the effect of invoking 'Collection' TypeError: Collection.aggregate is not a function
 at Meteor.methods.Totals

I get the above error, when I use aggregate but it does give the results, not sure what is the issue about!!

Collection.aggregate(pipeline);

The following is my packages:
meteor-platform
underscore
materialize:materialize
useraccounts:materialize
less
useraccounts:core
iron:router
accounts-password
sacha:spin
aldeed:collection2
aldeed:autoform
gildaspk:autoform-materialize
pcel:serialize
pcel:loading
matb33:collection-hooks
alethes:pages
meteorhacks:kadira
momentjs:moment
alanning:roles
digilord:faker
pascoual:pdfkit
meteorhacks:aggregate

any suggestions!!

**Comment by arunoda** [comment]
You can't use aggregate in the client. That's the error.

**Comment by suryaiiit** [comment]
Thanks, my bad. I've wrote in Meteor.method but included under lib, when moved tp server no more errors - I was thinking it is not under client, but then lib will also come under client - realised it late.
Once thanks for the help.
