### ISSUE TITLE
BUG? Mongo aggregate() using $out is not reactive (however collection is reactive)

### ISSUE THREAD

**Issue by keyscores** [meteorhacks/meteor-aggregate#23]
Mongo's aggregation pipeline is very useful, however using it correctly in Meteor fails silently.

I'm posting here since the community has not succeeded in solving it.
http://stackoverflow.com/questions/31620268/why-is-mongo-aggregation-not-reactive-in-meteor
https://forums.meteor.com/t/why-is-mongo-aggregation-not-reactive-in-meteor/7462

SPEC:
Using  Collection.aggregate({ $out: "<output-collection>" }) will output the result of an aggregation pipeline to a mongo collection called <output-collection>. Changes to this <output-collection> should be observable by the meteor server, and UI.

PROBLEM:
Server is not observing the changes to  <output-collection>.  Using $out *DOES* successfully create <output-collection> (which can be queried in the Mongo console). Also <output-collection> can be queried from the browser.

The <output-collection> is not invalid. All changes to those documents -- in mongo console for example-- will appear reactively in the UI. The data is not being observed on the server, in repo below see serverMain.js line 8 observeChanges.

REPRODUCING:
See the github with an app that reproduces the error. Just run 'meteor' and go to http://localhost:3000 to see the walk-through to reproduce.
https://github.com/keyscores/meteor-aggregation-issue

DEPENDENCIES:
The app uses meteorhacks:aggregate, a thin wrapper on the Mongo.aggregate()
https://github.com/meteorhacks/meteor-aggregate/

REFERENCE:
Aggregate and  $out:
http://docs.mongodb.org/manual/reference/operator/aggregation/out/

**Comment by keyscores** [comment]
https://github.com/meteor/meteor/issues/4947

**Comment by keyscores** [comment]
@arunoda Can I please get your input on this? Here is a repo that reproduces the bug: https://github.com/keyscores/meteor-aggregation-issue

Thanks in advance!

**Comment by arunoda** [comment]
This package is build to expose the `aggregate` API method from the node and we make it fiber aware.
It was harder to do in early days. Now it's simple like this and you don't need this package.

``` js
var nodeCollection = coll.rawCollection();
coll.aggregate = Meteor.wrapAsync(nodeCollection.aggregate, nodeCollection);
```

This is a pretty simple package.

There is no reactivity built into this and I don't know a solution for reactivity for aggregations other than polling.

**Comment by 0o-de-lally** [comment]
Thanks Arunoda!
Why would it not be reactive? The collection is no different than a collection created in mongo console (which is reactive).
What I mean: I do get reactive updates from mongo console, but not when using aggregate().
