### ISSUE TITLE
Does not work with Meteor.users (my code is on server side)

### ISSUE THREAD

**Issue by mwarren2** [meteorhacks/meteor-aggregate#27]
I have seen issue #4, but I'm afraid that this package still does not work with **Meteor.users**.
I've spent the whole day trying to get this to work, but it simply won't. (I have the very latest Meteor 1.2 version, for what it's worth).

_Background_: I had thought it would be a good idea to add customer orders to the user.profile - seemed like an obvious place to put them. So there is an **orders[]** array under **user.profile**.
So to see the latest orders I need to unwind this array from all the user records.

The following code works nicely in the mongo console:
    > db.users.aggregate([{$match: {}}, {$project: {profile: 1}}, {$unwind: '$profile.orders'}]);

So now here's my (very simple) server code:

```
Meteor.methods({
    getOrders: function(){
        return Meteor.users.aggregate([{$match: {}}, {$project: {profile: 1}}, {$unwind: '$profile.orders'}]);
    }
});
```

This fails with the following error message:

```
I20151021-21:54:50.969(2)? Exception while invoking method 'getOrders' TypeError: Object [object Object] has no method 'aggregate'
I20151021-21:54:50.969(2)?     at [object Object].Meteor.methods.getOrders (meteor://💻app/server/methods.js:5:1)
I20151021-21:54:50.970(2)?     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1692:12)
I20151021-21:54:50.970(2)?     at meteor://💻app/livedata_server.js:708:19
I20151021-21:54:50.970(2)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151021-21:54:50.970(2)?     at meteor://💻app/livedata_server.js:706:40
I20151021-21:54:50.970(2)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20151021-21:54:50.971(2)?     at meteor://💻app/livedata_server.js:704:46
I20151021-21:54:50.971(2)?     at tryCallTwo (/Users/malcolm/.meteor/packages/promise/.0.5.0.15j1xzs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151021-21:54:50.971(2)?     at doResolve (/Users/malcolm/.meteor/packages/promise/.0.5.0.15j1xzs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151021-21:54:50.971(2)?     at new Promise (/Users/malcolm/.meteor/packages/promise/.0.5.0.15j1xzs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
```

**Comment by mwarren2** [comment]
I can confirm that it works with a different collection.
It's just Meteor.users that gives the problem

**Comment by mwarren2** [comment]
I can do this manually to get it working - with the following code:

```
Meteor.methods({

getOrders: function(){

    var rawUsers = Meteor.users.rawCollection();
    var aggregateQuery = Meteor.wrapAsync(rawUsers.aggregate, rawUsers);
    var pipeline = [
        {$match: {}},
        {$project: {profile: 1, emails: 1}},
        {$unwind: '$profile.orders'}
    ];
    var result = aggregateQuery(pipeline);

    return result;
}


});
```

This works. Even though it appears to be the much the same as the code in the package.

**Comment by reywood** [comment]
I seem to be able to use `aggregate` on `Meteor.users` with no problem. If you open `meteor shell` and execute `Meteor.users.aggregate([{$group: { _id: null, sum: { $sum: 1 } } }]);` do you get the same error?

**Comment by mwarren2** [comment]
Yes, same error

```
bash-3.2$ meteor shell

Welcome to the server-side interactive shell!

Tab completion is enabled for global variables.

Type .reload to restart the server and the shell.
Type .exit to disconnect from the server and leave the shell.
Type .help for additional help.
```

> Meteor.users.aggregate([{$group: { _id: null, sum: { $sum: 1 } } }]);
> TypeError: Object [object Object] has no method 'aggregate'
>     at [object Object]:1:-48
>     at Script.(anonymous function) [as runInThisContext](vm.js:41:22)
>     at /Users/malcolm/git/malcolm-warren/sagrona/.meteor/local/build/programs/server/shell-server.js:305:27
>     at /Users/malcolm/.meteor/packages/meteor-tool/.1.1.10.1ydyxfw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/meteor-promise/fiber_pool.js:33:40
> Meteor.users.aggregate([{$group: { _id: null, sum: { $sum: 1 } } }]);
> TypeError: Object [object Object] has no method 'aggregate'
>     at [object Object]:1:-48
>     at Script.(anonymous function) [as runInThisContext](vm.js:41:22)
>     at /Users/malcolm/git/malcolm-warren/sagrona/.meteor/local/build/programs/server/shell-server.js:305:27
>     at /Users/malcolm/.meteor/packages/meteor-tool/.1.1.10.1ydyxfw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/meteor-promise/fiber_pool.js:33:40

I can confirm that the package is installed, of course, in case the obvious question came to mind! 
It's there in the packages.

**Comment by mwarren2** [comment]
I can run this code on the 'translations' collection without errors:

```
       Translations.aggregate([{$match: {}}]);
```

But this code gives the usual error:

```
       Meteor.users.aggregate([{$match: {}}]);

Exception while invoking method 'getOrders' TypeError: Object [object Object] has no method 'aggregate'
```

**Comment by reywood** [comment]
Does running `Meteor.users instanceof Mongo.Collection` in the shell return `true`? If not, I'd start to wonder if you have a package that is wrapping `Meteor.users`.

**Comment by mwarren2** [comment]
Returns false.

However: 

```
Meteor.users instanceof Meteor.Collection
```

returns true.

That's interesting because I started using Meteor after version 1.0 had arrived.

Thank you very much for your insights and ideas.
Do you have any idea where I should go from here? Is there any way of converting to a Mongo.Collection, for example?

**Comment by reywood** [comment]
This is a kludgy solution, but will probably work. Put the following somewhere in your server side code.

``` javascript
Meteor.Collection.prototype.aggregate = Mongo.Collection.prototype.aggregate;
```

What version of Meteor are you running? It's odd that Meteor.Collection is not an alias for Mongo.Collection. Running `Meteor.Collection === Mongo.Collection` returns true in my mongo shell.

**Comment by mwarren2** [comment]
Meteor.Collection === Mongo.Collection returns false.
I have 1.2.1

I have two apps, both at 1.2.1
a) the site
b) site admin

The site returns **true**, the admin app returns **false**

So maybe, like you said in an earlier post, I should be looking for something that's wrapping Mongo.Collection.
I shall compare packages from the two apps and see what's different. 
Then I'll start searching the code.

Thanks.

**Comment by reywood** [comment]
If it **is** a wrapping problem, something is probably wrapping `Meteor.users` directly (not `Mongo.Collection`) since your other collections have the `aggregate` method.

**Comment by mwarren2** [comment]
Your logic is impeccable .. 
that narrows it down a bit

**Comment by mwarren2** [comment]
I'm glad to say that this problem has gone away.
I presume that ordinary maintenance and updating and .... I don't know what, has removed the offending code.
So I can close this.
Thanks for your help.

**Comment by adrianblynch** [comment]
I have this same issue.

Reinstalled meteor today, along with `accounts`, `accounts-ui` and `accounts-google`.

@mwarren2 - Did you do anything in particular to trigger the fix?

Running: `Meteor.Collection === Mongo.Collection` just before trying to aggregate the users, I get `true`.

To get on with things, I removed the aggregate and mapped my fields manually.

Still intrigued as to what fixed it for some...

**Comment by mwarren2** [comment]
@adrianblynch I wish I could help, but I left the problem in the cooler for a while, and when I came back the problem had gone.
All I did was the usual maintenance, upgrading, and so on. 
The insights @reywood gives here are pretty interesting. 
Apart from going through his clues, the only advice I can give is to look out for anything that hasn't been worked on for a while, anything that looks like it's gone out of style, and try to replace it with something newer.

**Comment by adrianblynch** [comment]
Cheers.

I think I'll try and rep. in a new project with only the users collection and see what package causes the issues.

Will report back when I know more.

**Comment by sunlee-newyork** [comment]
+1, having the same issue here now with 1.4.1.1 using `accounts-base`, `accounts-password`, and `alanning:roles`.

**Comment by sairamdevarashetty** [comment]
+1 

*\* As I am looking the function definition **
`function (pipelines) {                          
{ '$project': { w: [Object] } },
 return this._collection.aggregate(pipelines);                                       
 }`

but the collection  `Meteor.users` doesn't have the function `aggregate`
