### ISSUE TITLE
Meteor@1.0.1

### ISSUE THREAD

**Issue by Laboratory** [meteorhacks/meteor-aggregate#3]
After added this package to my project

``` bash
meteorhacks:aggregate           1.1.0  Proper MongoDB aggregations support for Meteor
```

Collection.aggregate is undefined

What I need to do?

**Comment by dropfen** [comment]
@Laboratory 
its depending on collection-utils, did you have it installed?

**Comment by Laboratory** [comment]
@dropfen I use this package. Depending from collection-utils.
