### ISSUE TITLE
when will MongoDB 3.6 be supported?

### ISSUE THREAD

**Issue by maxfriedmann** [meteorhacks/meteor-aggregate#48]
I updated to Meteor 1.7, without changing the code, I now get an AggregationCursor returned and not the result of the last aggregation, see http://mongodb.github.io/node-mongodb-native/3.0/api/AggregationCursor.html

**Comment by muksyd** [comment]
Same here. I have tried using async/await along with .toArray() with the cursor but unable to figure out how to? Any ideas?

**Comment by maxfriedmann** [comment]
yes sure, the node-mongodb driver works as described in the documentation. Meteor also updated that lib internally to v3.0.7 which is great. It's just this package here that hasn't adopted that yet :)

I couldn't really switch to async/await in that part of the code, so I wrapped it the callback way: 

```typescript
const pipelineCursor = Meteor.users["aggregate"]([ ... ]);
const firstElem: any = Meteor.wrapAsync(pipelineCursor.next, pipelineCursor)();
```

**Comment by jadus** [comment]
#47 is fixing this issue

**Comment by muksyd** [comment]
Thanks @maxfriedmann.  That was helpful. We use aggregation quite a bit throughout our app so this might be some work to identify all over and fix.

@jadus Great! Thanks for the reference. I am switching to https://github.com/sakulstra/meteor-aggregate considering there are PRs waiting here since 2015. shout out to @sakulstra for the fork!!

**Comment by gustawdaniel** [comment]
Simplest solution of resolve this problem that I found is:

    meteor remove meteorhacks:aggregate  
    meteor add sakulstra:aggregate

It has the same interface but works with Meteor 1.7

**Comment by ahhatem** [comment]
Alternatively, you use the native rawCollection like this:


```
Meteor.methods({
  async aggregateMyStuff() {
    const pipeline = [ ... ];
    const options = { ... };
    let result = await (MyCollection.rawCollection().aggregate(pipeline, options)).toArray();
    return result;
  },
});
```

**Comment by evolross** [comment]
I'm actually wanting to call `MyCollection.rawCollection().aggregate()` _with_ a callback and not run it synchronously. As I'm worried about blocking the event loop. Is there a way to call `aggregate` and pass a callback that fires when it's done to process the results?

**Comment by maxfriedmann** [comment]
Native aggregation works now perfectly!
