### ISSUE TITLE
Casting issue with Mongo ObjectId()

### ISSUE THREAD

**Issue by TheAncientGoat** [meteorhacks/meteor-aggregate#6]
Not sure if this is a Meteor core issue or to do with how the aggregate pipelines get processed, but trying a $match pipeline with a Mongo ObjectID ends up with the ObjectId object being converted to {_str:"blah"}, and not matching any documents.

**Comment by arunoda** [comment]
Could you please give some sample code for this. Then I can work on this easily.

**Comment by TheAncientGoat** [comment]
Code that demonstrates working Meteor string id code and broken Mongo ObjectID code
```js
//Define MyCollection collection first
        var myObjectID = new Meteor.Collection.ObjectID();
        var myDoc = {_id : myObjectID, foo : 'bar', count:1};
        MyCollection.insert(myDoc);
        //Match attempts
        var matchObjectId = {$match:{
            '_id' : myObjectID //gets cast into {_str:id} instead of being passed as an ObjectId object
        }};
        var matchObjectIdEJSON = {$match:{
            '_id' : EJSON.stringify(myObjectID) //Try matching EJSON representation, doesn't work
        }};

        console.log(matchObjectId);
        var res = MyCollection.aggregate([
            matchObjectId,
            {$group:{
                _id:  '$foo',
                total: {$sum: '$count'}
            }}
        ])
        console.log('Match with Mongo ObjectId')
        console.log(res);
        
        // Working example with Meteor ID strings

        var myDoc2 = {foo : 'bar', count:1};
        var myMeteorID = MyCollection.insert(myDoc2);
        var res = MyCollection.aggregate([
            {$match:{
                '_id' : myMeteorID
            }},
            {$group:{
                _id:  '$foo',
                total: {$sum: '$count'}
            }}
        ])
        console.log('Match with Mongo ObjectId')
        console.log(res);
```

**Comment by benstr** [comment]
`MyCollection` does not connect to anything? On line two `myObjectID` should be `MyCollection` and remove the `var` too. You want that variable to be global.

**Comment by TheAncientGoat** [comment]
Sorry, the comment was not about the code, it was to indicate that the Collection should be defined somewhere else. I'll update the code to make it clearer.

**Comment by benstr** [comment]
Oh, sorry, I should have caught that. Too early in the morning over here.

**Comment by arunoda** [comment]
If you want to use `_id` as objects in aggregations. You need convert it before. 
`Meteor.Collection.ObjectID` is a Meteor's implementation of ObjectID. Not the original npm module's implementation.

This is the correct way to handle it.

~~~js
var id = new Meteor.Collection.ObjectID();
var mongoId = new MongoInternals.NpmModule.ObjectID(id._str);
ABC.insert({_id: id});

var res = ABC.aggregate([
  {$match: {_id: mongoId}}
]);

console.log(res);
~~~

**Comment by TheAncientGoat** [comment]
Thanks arunoda, funny that Meteor's implementation works in other contexts though

**Comment by FranciscoGutierrez** [comment]
I had this problem today, on the client side I don't have any problems with meteor implementation. This only happens when using this meteor-aggregate package.

**Comment by jayjaydluffy** [comment]
Super thanks @arunoda. Exhausted almost 2 days of work trying to deal with `new MongoID(<hex>)` query for mapReduce (I'm referring to this project's fork _**fentas:mapreduce**_). It was later that I realized this project is the parent package so I went directly to the issues area and, boom!

**Comment by fly19890211** [comment]
Hello, thanks for the comment before. It worked well from Meteor 1.3.x but it's broken after updated to Meteor 1.4.2.x
Seems something wrong with serializeObjectID with parser.
